x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '5.1.0'
  publishedVersionMetadata:
    releaseNote: >-
      Syntasa platform release 5.1.0
    releaseTypes:
      - Feature
    recommended: true
  partnerId: syntasa-public
  solutionId: syntasa
  managedUpdates:
    kalmSupported: true
  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 2
          memory: 16384Mi

  images:
    '': {}
    syntasa-generic-processor:
      properties:
        containerImage:
          type: FULL

    kafka:
      properties:
        kafkaImage:
          type: FULL

    zookeeper:
      properties:
        zookeeperImage:
          type: FULL

    haproxy-ingress:
      properties:
        ingressImage:
          type: FULL

    defaultbackend:
      properties:
        defaultBackendImage:
          type: FULL

    cloudsql-proxy:
      properties:
        sqlProxyImage:
          type: FULL

    syntasa-infrastructure-service:
      properties:
        syntasaInfrastructureServiceImage:
          type: FULL

    syntasa-api-service:
      properties:
        syntasaApiServiceImage:
          type: FULL

    syntasa-auth-service:
      properties:
        syntasaAuthServiceImage:
          type: FULL

    syntasa-composer-service:
      properties:
        syntasaComposerServiceImage:
          type: FULL

    syntasa-mlflow:
      properties:
        syntasaMlflowServiceImage:
          type: FULL

    syntasa-data-gateway-service:
      properties:
        syntasaDataGatewayServiceImage:
          type: FULL

    syntasa-event-engine-service:
      properties:
        syntasaEventEngineServiceImage:
          type: FULL

    syntasa-execution-service:
      properties:
        syntasaExecutionServiceImage:
          type: FULL

    syntasa-job-scheduler-service:
      properties:
        syntasaJobSchedulerServiceImage:
          type: FULL

    syntasa-notification-service:
      properties:
        syntasaNotificationServiceImage:
          type: FULL

    syntasa-runtime-service:
      properties:
        syntasaRuntimeServiceImage:
          type: FULL

    syntasa-alert-service:
      properties:
        syntasaAlertServiceImage:
          type: FULL

    syntasa-state-service:
      properties:
        syntasaStateServiceImage:
          type: FULL

    syntasa-app-preview:
      properties:
        syntasaAppPreviewImage:
          type: FULL

    syntasa-app-configuration-service:
      properties:
        syntasaAppConfigurationImage:
          type: FULL

    syntasa-app-platform:
      properties:
        syntasaAppPlatformImage:
          type: FULL

    syntasa-app-business:
      properties:
        syntasaAppBusinessImage:
          type: FULL

    syntasa-app-appdatagateway:
      properties:
        syntasaAppAppdatagatewayImage:
          type: FULL

    syntasa-app-apigateway:
      properties:
        syntasaAppApigatewayImage:
          type: FULL

form:
  - widget: help
    description: |-
      <h2>Thank you for your interest in SYNTASA</h2>

      <p>Before deploying the SYNTASA application from Google Marketplace, you must request a <a href="https://syntasa.com/form/gcp-marketplace-license-request">Syntasa license key</a> for a free trial.</p>
      <p><b>**This must be done prior to installing SYNTASA in the GCP Marketplace**</b></p>
      <p>Once requested, SYNTASA representatives will respond with a license key that you can use to deploy along with more detailed instructions</p>

      <p>For more information about the SYNTASA Google Marketplace Configuration Parameters on the left, please visit the following guide:</p>

      <a href="https://github.com/syntasa-dev/syntasa-google-marketplace/blob/master/docs/MARKETPLACE_CONFIG_OPTIONS.md#syntasa-google-cloud-marketplace-configuration-options">Syntasa Marketplace Installation and Configuration Documentation</a>

      <p>For more information about the SYNTASA solution please visiting the following github repo:</p>

      <a href="https://github.com/syntasa-dev/syntasa-google-marketplace#syntasa-customer-intelligence-platform-for-google-marketplace">Syntasa Marketplace Installation and Configuration Documentation</a></p>

      <p>For any additional support please visit: <a href="https://help.syntasa.com">help.syntasa.com</a></p>

properties:
  name:
    type: string
    default: "syntasa"
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    default: "default"
    x-google-marketplace:
      type: NAMESPACE

  syn_license:
    type: string
    title: License key.  Please see documentation (Required)
    default: ""
    x-google-marketplace:
      type: STRING

  syn_secret_key:
    type: string
    title: Secret Key.  Please see documentation (Required)
    default: ""
    x-google-marketplace:
      type: MASKED_FIELD

  static_ip_address:
    type: string
    title: IP Address of Reserved External IP (Optional)
    default: ""
    x-google-marketplace:
      type: STRING

  whitelist_ips:
    type: string
    title: Source IP Address filter
    description: Comma separated list of IP Addresses to whitelist.
    default: "0.0.0.0/0"

  metastore_connection_name:
    type: string
    title: External Metastore Connection Name (Required)
    default: ""
    x-google-marketplace:
      type: STRING

  metastore_connection_user:
    type: string
    title: External Metastore Username (Required)
    default: ""
    x-google-marketplace:
      type: STRING

  metastore_connection_password:
    type: string
    title: External Metastore Password (Required)
    default: ""
    x-google-marketplace:
      type: MASKED_FIELD

  infrastructure_service_account:
    type: string
    title: GCP IAM Role for Infrastructure Services (Required)
    default: ""
    x-google-marketplace:
      type: STRING

  syn_kube_service_account:
    type: string
    title: Syntasa Service Account Agent
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["secrets", "configmaps", "services", "endpoints", "nodes", "pods", "persistentvolumes", "pods/log"]
                verbs: ["*"]
              - apiGroups: [""]
                resources: ["events"]
                verbs: ["*"]
              - apiGroups: ["extensions", "apps"]
                resources: ["ingresses", "ingresses/status", "deployments"]
                verbs: ["*"]

  syn_kube_storage_class:
    type: string
    title: Storage Class
    default: "pd-standard"
    description: You can choose an existing storageclass or a newly created Storage Class will be provisioned with "pd-ssd"
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  syn_kube_storage_class_size:
    type: string
    title: Storage size for persistent volumes
    description: Storage Volume size for frontend/backend/platform services
    default: "20Gi"
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'

  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: TLS_CERTIFICATE_KEY
          base64EncodedCertificate: TLS_CERTIFICATE_CRT

required:
  - name
  - namespace
  - syn_license
  - syn_secret_key
  - whitelist_ips
  - metastore_connection_name
  - metastore_connection_user
  - metastore_connection_password
  - infrastructure_service_account
  - certificate