x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '7.1.2'
  publishedVersionMetadata:
    releaseNote: >-
      Syntasa platform release 7.1.2
    releaseTypes:
      - Feature
    recommended: true
  partnerId: syntasa-public
  solutionId: syntasa
  managedUpdates:
    kalmSupported: true
  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 2
          memory: 16384Mi

  images:
    '': {}
    ubbagent:
      properties:
        ubbagentImage:
          type: FULL
          value: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest
    syntasa-generic-processor:
      properties:
        containerImage:
          type: FULL

    kafka:
      properties:
        kafkaImage:
          type: FULL

    zookeeper:
      properties:
        zookeeperImage:
          type: FULL

    haproxy-ingress:
      properties:
        ingressImage:
          type: FULL

    defaultbackend:
      properties:
        defaultBackendImage:
          type: FULL

    cloudsql-proxy:
      properties:
        sqlProxyImage:
          type: FULL

    syntasa-infrastructure-service:
      properties:
        syntasaInfrastructureServiceImage:
          type: FULL

    syntasa-api-service:
      properties:
        syntasaApiServiceImage:
          type: FULL

    syntasa-auth-service:
      properties:
        syntasaAuthServiceImage:
          type: FULL

    syntasa-composer-service:
      properties:
        syntasaComposerServiceImage:
          type: FULL

    syntasa-mlflow:
      properties:
        syntasaMlflowServiceImage:
          type: FULL

    syntasa-data-gateway-service:
      properties:
        syntasaDataGatewayServiceImage:
          type: FULL

    syntasa-event-engine-service:
      properties:
        syntasaEventEngineServiceImage:
          type: FULL

    syntasa-execution-service:
      properties:
        syntasaExecutionServiceImage:
          type: FULL

    syntasa-job-scheduler-service:
      properties:
        syntasaJobSchedulerServiceImage:
          type: FULL

    syntasa-notification-service:
      properties:
        syntasaNotificationServiceImage:
          type: FULL

    syntasa-runtime-service:
      properties:
        syntasaRuntimeServiceImage:
          type: FULL

    syntasa-alert-service:
      properties:
        syntasaAlertServiceImage:
          type: FULL

    syntasa-state-service:
      properties:
        syntasaStateServiceImage:
          type: FULL

    syntasa-app-preview:
      properties:
        syntasaAppPreviewImage:
          type: FULL

    syntasa-app-configuration-service:
      properties:
        syntasaAppConfigurationImage:
          type: FULL

    syntasa-app-platform:
      properties:
        syntasaAppPlatformImage:
          type: FULL

    syntasa-app-business:
      properties:
        syntasaAppBusinessImage:
          type: FULL

    syntasa-app-appdatagateway:
      properties:
        syntasaAppAppdatagatewayImage:
          type: FULL

    syntasa-app-apigateway:
      properties:
        syntasaAppApigatewayImage:
          type: FULL

form:
  - widget: help
    description: |-
      <h2>Thank you for your interest in SYNTASA</h2>

      <p>Before deploying the SYNTASA application from Google Marketplace, you must request a <a href="https://syntasa.com/form/gcp-marketplace-license-request">Syntasa license key</a> for a free trial.</p>
      <p><b>**This must be done prior to installing SYNTASA in the GCP Marketplace**</b></p>
      <p>Once requested, SYNTASA representatives will respond with a license key that you can use to deploy along with more detailed instructions</p>

      <p>For more information about the SYNTASA Google Marketplace Configuration Parameters on the left, please visit the following guide:</p>

      <a href="https://github.com/syntasa-dev/syntasa-google-marketplace/blob/master/docs/MARKETPLACE_CONFIG_OPTIONS.md#syntasa-google-cloud-marketplace-configuration-options">Syntasa Marketplace Installation and Configuration Documentation</a>

      <p>For more information about the SYNTASA solution please visiting the following github repo:</p>

      <a href="https://github.com/syntasa-dev/syntasa-google-marketplace#syntasa-customer-intelligence-platform-for-google-marketplace">Syntasa Marketplace Installation and Configuration Documentation</a></p>

      <p>For any additional support please visit: <a href="https://help.syntasa.com">help.syntasa.com</a></p>

properties:
  name: 
    type: string
    x-google-marketplace:
      type: NAME
  namespace: 
    type: string
    x-google-marketplace:
      type: NAMESPACE
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  job.name:
    type: string
    default: "syntasa-package"
  job.ttlSecondsAfterFinished:
    type: integer
    default: 300
  job.activeDeadlineSeconds:
    type: integer
    default: 300
  job.serviceAccountName:
    type: string
  imagePullSecrets.name:
    type: string
  imageRepo:
    type: string
  installerVersion:
    type: string
  project:
    type: string
    default: "some-project"
  pullFromDockerhub:
    type: boolean
    default: true
  haproxy.name:
    type: string
    default: "syntasa-ingress"
  haproxy.serviceAccountName:
    type: string
  haproxy.service.loadBalancerIP:
    default: ""
    type: string
  haproxy.service.loadBalancerSourceRanges:
    default: "0.0.0.0/0"
    type: string
  configMap.name:
    type: string
    default: "syntasa-ingress-conf"
  secrets.docker.server:
    type: string
    default: "https://index.docker.io/v1/"
  secrets.docker.username:
    type: string
  secrets.docker.password:
    type: string
  secrets.cert.name:
    type: string
    default: "sma-certs"
  management.name:
    type: string
    default: "syntasa-management-console"
  management.ingress.name:
    type: string
    default: "syntasa-management-console"
  management.ingress.tls.host:
    type: string
    default: ""
  management.ingress.tls.secretName:
    type: string
    default: "sma-certs"
  roles.serviceAccount:
    type: string
    title: Syntasa Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          This service account is used to deploy the resources for the syntasa application including
          secrets, configmaps, ingresses, deployments, services, endpoints, nodes, pods, persistentvolumes, and monitor logs.
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: [ "", "apps" ]
                resources: [ "configmaps", "endpoints", "nodes", "pods", "services", "namespaces", "events", "serviceaccounts", "persistentvolumes", "persistentvolumeclaims", "secrets", "pods/log" ]
                verbs: [ "*" ]
              - apiGroups: [ "extensions", "apps", "networking.k8s.io" ]
                resources: [ "ingresses", "ingresses/status", "deployments", "ingressclasses" ]
                verbs: [ "*" ]
              - apiGroups: [ "apiextensions.k8s.io" ]
                resources: [ "customresourcedefinitions" ]
                verbs: [ "*" ]
              - apiGroups: [ "sparkoperator.k8s.io" ]
                resources: [ "*" ]
                verbs: [ "*" ]
              - apiGroups: [ "batch" ]
                resources: [ "*" ]
                verbs: [ "*" ]
              - apiGroups: [ "rbac.authorization.k8s.io" ]
                resources: [ "rolebindings", "roles" ]
                verbs: [ "*" ]
              - apiGroups: [ "v1" ]
                resources: [ "serviceaccounts" ]
                verbs: [ "*" ]

  certificate:
    type: string
    x-google-marketplace:
      type: TLS_CERTIFICATE
      tlsCertificate:
        generatedProperties:
          base64EncodedPrivateKey: TLS_CERTIFICATE_KEY
          base64EncodedCertificate: TLS_CERTIFICATE_CRT
required:
  - name
  - namespace
  - project
  - certificate