apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container_metadata.syntasa_app_platform.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container_metadata.syntasa_app_platform.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:   
        app: {{ .Values.container_metadata.syntasa_app_platform.name }}
    spec:
      serviceAccountName: {{ .Values.syn_kube_service_account }}
      volumes:
      - name: key-volume
        secret:
          secretName: syntasa-key
      containers:
      - image: "{{ .Values.syntasaAppPlatformImage }}"
        name: {{ .Values.container_metadata.syntasa_app_platform.name }}
        imagePullPolicy: Always
        env:
          - name: SYNTASA_ENVIRONMENT_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_provider_type
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_host
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_port
          - name: KAFKA_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_host
          - name: KAFKA_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_port
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_username
          - name: PG_SECRET
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_password
          - name: AUTH_SERVICE_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_auth_service_protocol
          - name: AUTH_SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                 name: {{ .Values.global.configMap.name }}
                 key: syntasa_app_auth_service_host
          - name: AUTH_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_auth_service_port
        volumeMounts:
        - name: key-volume
          readOnly: true
          mountPath: "/syn-app/server/services/platform/syntasa"
      imagePullSecrets:
      - name: {{.Values.global.imagePullSecret.name }}