apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.container_metadata.ingress.name }}
  name: {{ .Values.container_metadata.ingress.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: port-2
      port: 443
      nodePort: 32505
      protocol: TCP
  selector:
    run: {{ .Values.container_metadata.ingress.name }}
  {{ if .Values.static_ip_address }}
  loadBalancerIP: {{ .Values.static_ip_address }}
  {{- else}}
  loadBalancerIP: ""
  {{ end }}
  loadBalancerSourceRanges:
  {{- range splitList "," .Values.whitelist_ips }}
  - {{.}}
  {{- end }}