apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container_metadata.syntasa_composer_service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container_metadata.syntasa_composer_service.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.container_metadata.syntasa_composer_service.name }}
    spec:
      serviceAccountName: {{ .Values.syn_kube_service_account }}
      containers:
      - image: "{{ .Values.syntasaComposerServiceImage }}"
        name: {{ .Values.container_metadata.syntasa_composer_service.name }}
        imagePullPolicy: Always
        env:
          - name: COMPOSER_MLFLOW_SERVER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_composer_service_mlflow_server
          - name: COMPOSER_MLFLOW_ARTIFACT_BASE_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_composer_service_mlflow_base_path
          - name: COMPOSER_KAFKA_BROKER_LIST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_url
      imagePullSecrets:
      - name: {{.Values.global.imagePullSecret.name }}