apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container_metadata.syntasa_app_apigateway.name}}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container_metadata.syntasa_app_apigateway.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:   
        app: {{ .Values.container_metadata.syntasa_app_apigateway.name}}
    spec:
      serviceAccountName: {{ .Values.syn_kube_service_account }}
      volumes:
      - name: key-volume
        secret:
          secretName: syntasa-key
      containers:
      - image: "{{ .Values.syntasaAppApigatewayImage }}"
        name: {{ .Values.container_metadata.syntasa_app_apigateway.name}}
        imagePullPolicy: Always
        env:
          - name: SYNTASA_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_protocol
          - name: SYNTASA_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_hostname
          - name: VERSION
            value: {{ .Values.global.image.tag }}
          - name: LOCALHOST
            value: "localhost"
          - name: HTTP_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_http_enable
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_http_port
          - name: HTTPS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_https_enable
          - name: KAFKA_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_host
          - name: KAFKA_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_port
          - name: ANALYTICS_ENABLED
            value: "false"
          - name: SYNTHESIZER_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_synthesizer_enable
          - name: COMPOSER_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_composer_enable
          - name: ORCHESTRATOR_ENABLED
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_orchestrator_enable
          - name: INFRA_METADATA_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_api_service_protocol
          - name: INFRA_METADATA_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_api_service_host
          - name: INFRA_METADATA_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_api_service_port
          - name: TOKEN_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_token_timeout
          - name: AUTH_SERVICE_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_auth_service_protocol
          - name: AUTH_SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                 name: {{ .Values.global.configMap.name }}
                 key: syntasa_app_auth_service_host
          - name: AUTH_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_auth_service_port
          - name: STATE_SERVICE_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_state_service_protocol
          - name: STATE_SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_state_service_host
          - name: STATE_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_state_service_port
          - name: RUNTIME_SERVICE_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_runtime_service_protocol
          - name: RUNTIME_SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_runtime_service_host
          - name: RUNTIME_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_runtime_service_port
          - name: JOB_MANAGEMENT_SERVICE_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_job_scheduler_service_protocol
          - name: JOB_MANAGEMENT_SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_job_scheduler_service_host
          - name: JOB_MANAGEMENT_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_job_scheduler_service_port
          - name: EXECUTION_SERVICE_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_execution_service_protocol
          - name: EXECUTION_SERVICE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_execution_service_host
          - name: EXECUTION_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_app_execution_service_port

        volumeMounts:
        - name: key-volume
          readOnly: true
          mountPath: "/syn-app/server/services/apiGateway/syntasa"
      imagePullSecrets:
      - name: {{.Values.global.imagePullSecret.name }}