apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.namespace }}
  labels:
    run: {{ .Values.job.name }}
spec:
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        run: {{ .Values.job.name }}
    spec:
      serviceAccountName: {{ .Values.roles.serviceAccount }}
      automountServiceAccountToken: true
      restartPolicy: "OnFailure"
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
      - name: {{ .Values.job.name }}
        image: "{{ .Values.syntasaPackageImage }}"
        imagePullPolicy: "Always"
        env:
        - name: SYNTASA_HOSTNAME
          value: "{{ .Values.management.ingress.tls.host }}"
        - name: SYNTASA_PULL_POLICY
          value: "Always"
        - name: GCP_PROJECT_NAME
          value: {{ .Values.project }}
        - name: IMAGE_REPO
          value: "{{ .Values.imageRepo }}"
