apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.container_metadata.syntasa_infrastructure_service.name }}
spec:
  type: NodePort
  ports:
    - port: 4440
      nodePort: 31440
      targetPort: 4440
  selector:
    app: {{ .Values.container_metadata.syntasa_infrastructure_service.name }}