apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container_metadata.syntasa_notification_service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container_metadata.syntasa_notification_service.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.container_metadata.syntasa_notification_service.name }}
    spec:
      containers:
      - image: "{{ .Values.syntasaNotificationServiceImage }}"
        name: {{ .Values.container_metadata.syntasa_notification_service.name }}
        imagePullPolicy: Always
        env:
          - name: NOTIFICATION_SERVICE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_username
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_password
          - name: NOTIFICATION_SERVICE_PERSISTENCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_url
          - name: NOTIFICATION_SERVICE_BROKER_LIST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_url
        ports:
        - containerPort:  {{ .Values.container_metadata.syntasa_notification_service.container_port | int }}
          name: notify-svc-prt
      imagePullSecrets:
      - name: {{.Values.global.imagePullSecret.name }}