apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.container_metadata.syntasa_mlflow_service.service_name}}
spec:
  ports:
    - port: {{ .Values.container_metadata.syntasa_mlflow_service.container_port | int }}
  selector:
    app: {{ .Values.container_metadata.syntasa_mlflow_service.name }}