apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container_metadata.syntasa_alert_service.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 8400
      nodePort: 31400
  selector:
    app: {{ .Values.container_metadata.syntasa_alert_service.name }}