apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container_metadata.syntasa_notification_service.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.container_metadata.syntasa_notification_service.container_port | int }}
      nodePort: 31300
  selector:
    app:  {{ .Values.container_metadata.syntasa_notification_service.service_name }}