apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container_metadata.kafka.service_name}}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 31092
      name: external
      nodePort: 31092
    - port: 31093
      name: internal
      nodePort: 31093
    - port: 31094
      name: internal-1
      nodePort: 31094
  selector:
    app: {{ .Values.container_metadata.kafka.name }}