apiVersion: v1
kind: Secret
metadata:
  name: syntasa-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.key: {{ .Values.TLS_CERTIFICATE_KEY }}
  tls.crt: {{ .Values.TLS_CERTIFICATE_CRT }}
type: kubernetes.io/tls