apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container_metadata.syntasa_app_configuration.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.container_metadata.syntasa_app_configuration.container_port }}
  selector:
    app: {{ .Values.container_metadata.syntasa_app_configuration.name }}
