apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container_metadata.sql_proxy.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ .Values.container_metadata.sql_proxy.name }}