apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container_metadata.syntasa_state_service.service_name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.container_metadata.syntasa_state_service.container_port }}
  selector:
    app: {{ .Values.container_metadata.syntasa_state_service.name }}