apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container_metadata.syntasa_state_service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container_metadata.syntasa_state_service.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.container_metadata.syntasa_state_service.name }}
    spec:
      containers:
      - image: "{{ .Values.global.image.repository }}/{{ .Values.container_metadata.syntasa_state_service.image_name }}:{{ .Values.global.image.tag }}"
        name: {{ .Values.container_metadata.syntasa_state_service.name }}
        imagePullPolicy: Always
        env:
          - name: STATE_SERVICE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_username
          - name: STATE_SERVICE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_password
          - name: STATE_SERVICE_DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_postgres_url
          - name: STATE_SERVICE_KAFKA_BROKER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_kafka_service_url
          - name: STATE_SERVICE_GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_state_service_consumer_id
          - name: STATE_SERVICE_METRICS_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMap.name }}
                key: syntasa_state_service_metrics_url
        ports:
        - containerPort: {{ .Values.container_metadata.syntasa_state_service.container_port }}
          name: state-svc-port
      imagePullSecrets:
      - name: {{.Values.global.imagePullSecret.name }}