name: "syntasa-application"
namespace: default
project: "syntasa-dev"
gcpServiceAccount: ""
reportingSecret: ""
publishedVersion: "7.1.2"

imageRepo: ""
ubbAgentImage: "gcr.io/cloud-marketplace-tools/metering/ubbagent:latest"
haproxyIngressImage: ""
syntasaInstallerAgentImage: ""
syntasaManagementImage: ""
syntasaManagementAuthImage: ""
syntasaManagementConsoleImage: ""
syntasaPackageImage: ""

job:
  name: syntasa-package
  ttlSecondsAfterFinished: 300
  activeDeadlineSeconds: 300

imagePullSecrets:
  name: syn-creds

haproxy:
  name: syntasa-ingress
  ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
    - name: stat
      containerPort: 1936
  service:
    name: syntasa-ingress
    port: 443
    targetPort: 443
    type: LoadBalancer
    loadBalancerIP: ""
    loadBalancerSourceRanges: "0.0.0.0/0"
    loadBalancerHostname: ""

secrets:
  cert:
    name: sma-certs
  docker:
    server: https://index.docker.io/v1/
    username: your-docker-username
    password: your-docker-password

management:
  container_metadata:
    management_name: syntasa-management
    management_console_name: syntasa-management-console
    management_auth_name: syntasa-management-auth
  ingress:
    name: syntasa-management-console
    tls:
      secretName: sma-certs
      host: ""

roles:
  serviceAccount: "sma-sa"

deployerServiceAccount: "deployer-sa"

TLS_CERTIFICATE_CRT: eW91ci1jZXJ0aWZpY2F0ZQo=
TLS_CERTIFICATE_KEY: eW91ci1rZXkK