applicationApiVersion: v1beta1

properties:
  name:
    type: string
    default:
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  syntasa_test_image_name:
    type: string
    default: "syntasa"

required:
- name
- namespace